using Content.Shared._RMC14.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._RMC14.Ghost;

[GenerateTypedNameReferences]
[Virtual]
public partial class RMCVoteChoiceControl : Control
{
    public RMCVoteChoiceControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void Set(string name)
    {
        NameLabel.SetMessage(name);
    }

    public void Set(FormattedMessage msg)
    {
        NameLabel.SetMessage(msg);
    }
}
