- type: entity
  parent: MarkerBase
  id: RMCRaffleEventSpawner
  name: Raffle Event Spawner
  suffix: RMC
  abstract: true
  components:
  - type: Sprite
    sprite: _RMC14/Markers/landmarks.rsi
    layers:
    - state: corpse_spawner
  - type: RMCGhostRoleCandidatePicker
  - type: GhostRoleMobSpawner
    availibleTakeovers: 0

- type: entity
  parent: RMCRaffleEventSpawner
  id: RMCBehemothRaffleEventSpawner
  name: Behemoth Event Spawner
  components:
  - type: RMCGhostRoleCandidateChoiceXeno
    jobRequirement: RMCXenoBehemoth
  - type: RMCGhostRoleCandidatePicker
    optInAction: ActionOptInBehemoth
    candidatePopup: rmc-ghost-picker-popup-behemoth
  - type: GhostRoleMobSpawner
    prototype: RMCXenoBehemoth
  - type: GhostRole
    makeSentient: true
    allowSpeech: true
    allowMovement: true
    name: cm-xeno-name
    description: cm-xeno-description
    raffle:
      settings: short
    
