- type: job
  parent: CMJobXenoBase
  id: RMCXenoBehemoth
  name: cm-job-name-xeno-behemoth
  playTimeTracker: RMCXenoBehemoth
  requirements:
  - !type:TotalJobsTimeRequirement
    group: CMJobsXeno
    time: 36000 # 10 hours
  - !type:TotalJobsTimeRequirement
    group: CMJobsXenoDrones
    time: 18000 # 5 hours
  - !type:TotalJobsTimeRequirement
    group: CMJobsXenoTierThree
    time: 10800 # 3 hours
  requireAdminNotify: true

- type: playTimeTracker
  id: RMCXenoBehemoth
  isXeno: true
